version: "3"
services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - MONGO_SECRET=${MONGO_SECRET}
      - MONGO_URL=${MONGO_URL}
      - FOODIES_MAIL=${FOODIES_MAIL}
      - FOODIES_PWD=${FOODIES_PWD}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: {}
